version: "1.0"
services:
  db:
    image: mysql:8.0
    container_name: db
    networks:
      - dev_network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: url_shortener
    ports:
      - 3309:3306
    volumes:
      - data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - dev_network
    ports:
      - 6379:6379

  go:
    build:
      context: .
      dockerfile: dockerfile
    image: go:1.0
    container_name: go
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/url_shortener:rw
    networks:
      - dev_network
    command: sh -c "make run"
    depends_on:
      - db
    tty: true

networks:
  dev_network:
    external: true
volumes:
  data: {}
