version: "2.0"
services:
  db:
    image: mysql:8.0
    container_name: db
    networks:
      - dev_network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: url_shortener
    volumes:
      - data:/var/lib/mysql

  proxy_server:
    image: nginx:1.23
    container_name: proxy_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/url_shortener.conf:/etc/nginx/conf.d/url_shortener.conf
    networks:
      - dev_network
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - dev_network
    ports:
      - 6379:6379

  go:
    build:
      context: .
      dockerfile: dockerfile
    image: go:1.21
    container_name: go
    volumes:
      - .:/var/www/url_shortener:rw
    networks:
      - dev_network
    command: sh -c "make run"
    depends_on:
      - db
    tty: true

networks:
  dev_network:
    external: true
volumes:
  data: {}
